#!/usr/bin/env sh

# BigSur compatibility
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_animation_duration 0
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.3
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_border_blur off
yabai -m config window_border_radius 8
yabai -m config active_window_border_color 0xff228ec3
yabai -m config normal_window_border_color 0xff8866cc
yabai -m config insert_feedback_color 0xaad75f5f
yabai -m config insert_feedback_color 0x00ffffff
yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# General space settings

yabai -m config layout bsp

yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 06

yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label social
yabai -m space 4 --label mix

# List of rules

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="CleanMyMac X" app="^CleanMyMac X$" manage=off
yabai -m rule --add label="Karabiner Elements" app="^Karabiner" manage=off
yabai -m rule --add label="PDF Expert" app="^PDF Expert$" grid=1:2:1:0:1:1 manage=off
yabai -m rule --add label="Books" app="^Books" space=mix
yabai -m rule --add label="Calibre" app="^calibre" space=mix
yabai -m rule --add label="Edge" app="^Microsoft Edge" space=web
yabai -m rule --add label="Wezterm" app="^WezTerm" space=code
yabai -m rule --add label="Alacritty" app="^Alacritty" space=code
yabai -m rule --add label="iTerm2" app="^iTerm2" space=code
yabai -m rule --add label="Discord" app="^Discord" space=social opacity=0.85
yabai -m rule --add label="Element" app="^Element" space=social opacity=0.85
yabai -m rule --add label="Messenger" app="^Messenger" space=social opacity=0.75

# Signals

# Auto stacking windows
yabai -m signal --add event=window_focused action="yabai -m window $YABAI_WINDOW_ID --insert stack"
yabai -m signal --add event=application_front_switched action='yabai -m window --insert stack'
yabai -m signal --add event=window_destroyed action='yabai -m window --insert stack'
yabai -m signal --add event=application_terminated action='yabai -m window --insert stack'

echo "yabai configuration loaded.."

# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
