#!/usr/bin/env sh

# >= BigSur compatibility
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config \
  mouse_follows_focus on \
  focus_follows_mouse autoraise \
  window_origin_display default \
  window_placement second_child \
  window_topmost off \
  window_shadow on \
  window_animation_duration 0.0 \
  window_opacity on \
  window_opacity_duration 0.0 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.8 \
  window_border off \
  window_border_hidpi on \
  window_border_width 3 \
  window_border_blur off \
  window_border_radius 12 \
  insert_feedback_color 0xff9dd274 \
  active_window_border_color 0xfff38ba8 \
  normal_window_border_color 0xff2a2f38 \
  split_ratio 0.50 \
  split_type auto \
  auto_balance on \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  layout bsp \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 06

yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label social
yabai -m space 4 --label mix

# List of rules
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="CleanMyMac X" app="^CleanMyMac X$" manage=off
yabai -m rule --add label="Karabiner Elements" app="^Karabiner" manage=off
yabai -m rule --add label="PDF Expert" app="^PDF Expert$" grid=1:2:1:0:1:1 manage=off
yabai -m rule --add label="Books" app="^Books" space=mix
yabai -m rule --add label="Calibre" app="^calibre" space=mix
yabai -m rule --add label="Microsoft Edge" app="^Microsoft Edge" space=web
yabai -m rule --add label="Firefox" app="^Firefox" space=web
# Using `cmacrae/emacs` nix build, this is unneccessary
# yabai -m rule --add label="Doom Emacs" app="Emacs" title!="^(  —  \(.*\)| *Minibuf.*\*)$" manage=on space=code
yabai -m rule --add label="Wezterm" app="^WezTerm" space=code
yabai -m rule --add label="Alacritty" app="^Alacritty" space=code
yabai -m rule --add label="iTerm2" app="^iTerm2" space=code
yabai -m rule --add label="Discord" app="^Discord" space=social opacity=0.95
yabai -m rule --add label="Element" app="^Element" space=social opacity=0.95
yabai -m rule --add label="Messenger" app="^Messenger" space=social opacity=0.95

# Signals

# Auto stacking windows
# yabai -m signal --add event=window_focused action="yabai -m window $YABAI_WINDOW_ID --insert stack"
# yabai -m signal --add event=application_front_switched action='yabai -m window --insert stack'
# yabai -m signal --add event=window_destroyed action='yabai -m window --insert stack'
# yabai -m signal --add event=application_terminated action='yabai -m window --insert stack'

echo "yabai configuration loaded.."

# YABAI_CERT=yabai-cert sh -c "$(curl -fsSL "https://git.io/update-yabai")" &
