# use with https://github.com/casey/just

# Display list of commands
@help:
  just --list

@themer:
  rm -f themer/*.lua
  fennel  --compile fnl/themer/rose-pine.fnl > themer/rose-pine.lua
  fennel  --compile fnl/themer/rose-pine-dawn.fnl > themer/rose-pine-dawn.lua

@compile:
  rm -f wezterm.lua
  fennel  --compile fnl/wezterm.fnl > wezterm.lua
