# use with https://github.com/casey/just

fennel_binary := 'fennel'
fennel_folder := 'fnl'
fennel_themer_folder := 'fnl/themer'

# Display list of commands
@help:
  just --list

# Remove compiled lua file
@clean:
  rm -f themer/*.lua
  rm -f *.lua

# Compile every fennel file into lua files
@compile: clean
  for file in {{fennel_themer_folder}}/*.fnl; do \
    {{fennel_binary}} --compile "$file" > "themer/$(basename ${file} .fnl).lua"; \
  done
  for file in {{fennel_folder}}/*.fnl; do \
    {{fennel_binary}} --compile "$file" > "$(basename ${file} .fnl).lua"; \
  done
